#!/bin/bash

# Проверка наличия аргументов
if [ "$#" -ne 2 ]; then
    echo "Использование: $0 <текст письма> <адрес электронной почты>"
    exit 1
fi

# Получение аргументов
text=$1
email=$2

# Отправка письма
echo "$text" | msmtp --file=/opt/nagios/etc/msmtprc "$email"

echo "Письмо отправлено на адрес $email"

