version: '3.8'

services:
  nginx1:
    image: custom-nginx
    container_name: nginx1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html
    networks:
      - webnet
    ports:
      - "9113:9113"  # Добавьте этот порт для экспорта метрик

  nginx2:
    image: custom-nginx
    container_name: nginx2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html
    networks:
      - webnet
    ports:
      - "9114:9113"  # Измените внешний порт для каждого контейнера

  nginx3:
    image: custom-nginx
    container_name: nginx3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html
    networks:
      - webnet
    ports:
      - "9115:9113"

  nginx4:
    image: custom-nginx
    container_name: nginx4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html
    networks:
      - webnet
    ports:
      - "9116:9113"

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - webnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  haproxy_exporter:
    image: prom/haproxy-exporter:latest
    container_name: haproxy_exporter
    ports:
      - "9101:9101"
    command:
      - '--haproxy.scrape-uri=http://haproxy:8404/stats;csv'
    networks:
      - webnet

  nagios:
    image: nagios_msmtp
    ports:
      - "8085:80"
    networks:
      - webnet
    volumes:
      - ./nagios-config/:/opt/nagios/etc
      - ./nagios-logs/:/opt/nagios/var

networks:
  webnet:

