FROM nginx:latest

# Установка зависимостей и Nginx Prometheus Exporter
RUN apt-get update && apt-get install -y wget \
    && wget -q https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz \
    && tar -xzf nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz \
    && mv nginx-prometheus-exporter /usr/local/bin/ \
    && rm nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz \
    && apt-get clean #\
    && rm -rf /var/lib/apt/lists/*

# Копирование конфигурационного файла Nginx
COPY /home/ec2-user/My_web_full/docker-nginx-haproxy-graffana-nagios/nginx/nginx.conf /etc/nginx/nginx.conf

# Настройка запуска Nginx и экспорта метрик
 CMD ["sh", "-c", "nginx -g 'daemon off;' & nginx-prometheus-exporter -nginx.scrape-uri http://localhost/nginx_status"]

