services:
  nodejs-app:
    image: jessehoch/pacman-nodejs-app:latest
    ports:
      - "8081:8080"  # Map port 8080 of the container to port 8081 on the host
    environment:
      MONGO_SERVICE_HOST: mongo
      MONGO_AUTH_USER: pacman
      MONGO_AUTH_PWD: pacman
      MONGO_DATABASE: pacman
    restart: unless-stopped

  mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongo-db:/data/db
      - ./mongo-init-db/init_user_db.js:/docker-entrypoint-initdb.d/init_user_db.js:ro  # Mount the initialization script directory
    restart: unless-stopped

volumes:
  mongo-db:
    driver: local
  mongo-initdb:
    driver: local
    driver_opts:
      type: none
      device: $PWD/mongo-init-db # Use absolute path for device
      o: bind

networks:
  default:
    external:
      name: pacman-network
